In [3]:
import pyreadr
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
RANDOM_STATE = 42
TEST_SIZE = 0.3

# Einecke2010Kidney (Gene expression)
Source: https://github.com/statOmics/HDDAData/blob/master/data/Einecke2010Kidney.rda

In [33]:
data = pyreadr.read_r("../Datasets/Einecke2010Kidney/Einecke2010Kidney.rda")["Einecke2010Kidney"]
print(data.shape)
display(data.head(3))

(250, 10001)

,Reject_Status,X211352_s_at,X239275_at,X1554536_at,X1558452_at,X1554249_a_at,X234382_x_at,X1557126_a_at,X1554865_at,X224489_at,...,X1556328_at,X1562010_x_at,X225265_at,X219651_at,X206674_at,X237553_at,X230028_at,X1566265_at,X238792_at,X224046_s_at
rownames,,,,,,,,,,,,,,,,,,,,,
GSM534173,0.0,2.369256,1.054915,1.249065,0.842188,0.991463,0.461967,-0.637490,1.450212,-0.086256,...,3.024731,0.886139,0.885123,0.705803,-0.393019,-0.662579,1.127099,1.482058,0.876832,-0.038226
GSM534125,0.0,-1.488201,-0.605784,-2.042745,0.947212,-0.966968,1.317226,0.651391,-3.063391,-0.898287,...,-1.524487,-0.556126,-1.300856,-1.414818,1.763672,-1.597220,0.271000,1.605595,-0.721801,-0.804238
GSM534044,0.0,0.556138,0.838207,-0.728721,0.354435,1.543933,-0.472268,-0.343074,-0.836987,-1.307204,...,-2.238545,0.357365,-0.599514,-0.320214,-0.932220,-0.221984,1.153710,1.622174,-0.148435,0.704653

In [34]:
data.rename(columns={"Reject_Status": "label"}, inplace=True)
data["label"] = data["label"].astype(int)
data.columns = [["label"] + list(range(len(data.columns))[:-1])]
data = data[list(range(len(data.columns))[:-1]) + ["label"]].copy()
data.columns = [col[0] if isinstance(col, tuple) else col for col in data.columns]

In [35]:
train_data, test_data = train_test_split(data, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=data["label"])

In [36]:
train_data["subset"] = "train"
test_data["subset"] = "test"
data = pd.concat([train_data, test_data], axis=0).reset_index(drop=True)
data.columns = [col[0] if isinstance(col, tuple) else col for col in data.columns]
data["label"] = data["label"].astype(int)
data

,0,1,2,3,4,5,6,7,8,9,...,9992,9993,9994,9995,9996,9997,9998,9999,label,subset
0,0.183642,-0.808002,0.757061,0.034529,-1.691963,1.498924,-0.648835,1.637611,-1.361226,-0.853824,...,0.073362,1.860767,-0.484340,-0.725581,1.132319,0.153071,-0.258534,-1.271537,0,train
1,-0.075563,-0.132280,-1.033774,0.954663,-1.738526,1.665426,-0.925967,1.052345,1.905630,-1.022174,...,0.982844,-0.128019,-1.112401,-0.252825,0.019207,-0.031537,0.426290,-0.693450,1,train
2,-1.557944,1.183841,0.915740,0.125931,0.304172,-1.169950,1.645214,-1.556818,-0.206314,-0.734457,...,-0.610162,-1.650369,-1.481633,0.451791,-0.777383,-2.253761,-0.140716,1.874622,0,train
3,-1.364607,1.251154,0.975923,-0.325284,0.574970,0.416173,2.116884,-0.409975,-0.301731,-1.347928,...,1.243601,-0.158799,-1.330164,0.278596,-0.265356,0.703576,0.342743,0.738098,0,train
4,-0.597536,-0.208939,0.031824,0.264499,-0.792139,-1.005075,-0.168357,-0.393647,-0.546094,0.073063,...,-1.596032,0.271326,0.278951,0.231645,-0.787302,-0.720604,-1.654160,-1.108226,0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,-0.045304,0.098200,0.462675,0.617799,-1.236766,-0.466957,-1.158400,0.470655,-0.085677,-0.150765,...,0.639915,-0.849114,0.910367,-1.121349,0.213185,-0.547388,-0.119982,0.328423,1,test
246,-0.115222,-0.498316,0.467083,-0.277389,-0.505282,0.172246,-0.958354,-0.210169,0.161404,0.561748,...,0.692640,0.726797,-0.061488,-0.121082,0.087248,0.683097,-0.825619,-1.053481,1,test
247,-0.502184,-0.235830,-0.264725,0.717197,-1.325940,-0.793194,-1.353534,-0.292195,-0.991381,-0.388188,...,-0.879481,-1.221680,0.007070,-0.661649,-0.031114,-0.789919,-1.761162,-1.088126,0,test
248,-0.992707,0.408546,-1.011508,-0.422938,-0.900868,-0.248821,-0.532738,-0.736003,-1.019876,-0.307306,...,-0.911675,-0.293741,0.895733,-0.949166,-1.383525,-0.654326,-0.672185,0.327222,0,test
249,0.787715,0.422310,-0.212361,-0.081114,1.630317,-0.868146,0.870158,-0.007602,1.521680,0.178408,...,1.135470,0.147381,-1.879046,0.376895,1.097960,0.927092,2.006433,0.949885,0,test

In [37]:
data.drop(columns=["subset"]).dtypes.unique(), data["label"].value_counts(normalize=True), data["subset"].value_counts(normalize=True), data.groupby("subset")["label"].value_counts(normalize=True), data.isna().sum().sum()

(array([dtype('float64'), dtype('int64')], dtype=object),
 label
 0    0.732
 1    0.268
 Name: proportion, dtype: float64,
 subset
 train    0.7
 test     0.3
 Name: proportion, dtype: float64,
 subset  label
 test    0        0.733333
         1        0.266667
 train   0        0.731429
         1        0.268571
 Name: proportion, dtype: float64,
 np.int64(0))

In [38]:
data.to_parquet("../Benchmark/einecke2010kidney.parquet", index=False)

# Alon1999 (Gene expression)
Source: https://github.com/statOmics/HDDAData/blob/master/data/Alon1999.rda

In [24]:
data = pyreadr.read_r("../Datasets/Alon1999/Alon1999.rda")["Alon1999"]
print(data.shape)
display(data.head(3))

(62, 2001)

,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X1991,X1992,X1993,X1994,X1995,X1996,X1997,X1998,X1999,X2000
0,t,8589.42,5468.24,4263.41,4064.94,1997.89,5282.33,2169.72,2773.42,7526.39,...,99.11,67.56,259.91,138.90,88.23,39.67,67.83,75.68,83.52,28.70
1,n,9164.25,6719.53,4883.45,3718.16,2015.22,5569.91,3849.06,2793.39,7017.73,...,126.79,92.24,96.28,150.59,82.24,85.03,152.20,186.57,44.47,16.77
2,t,3825.71,6970.36,5369.97,4705.65,1166.55,1572.17,1325.40,1472.26,3296.95,...,151.88,82.72,31.10,193.92,76.97,224.62,31.23,42.66,16.09,15.16

In [25]:
data.dtypes

Y         object
X1       float64
X2       float64
X3       float64
X4       float64
          ...
X1996    float64
X1997    float64
X1998    float64
X1999    float64
X2000    float64
Length: 2001, dtype: object

In [27]:
data.rename(columns={"Y": "label"}, inplace=True)
data.columns = [["label"] + list(range(len(data.columns))[:-1])]
data = data[list(range(len(data.columns))[:-1]) + ["label"]].copy()
data.columns = [col[0] if isinstance(col, tuple) else col for col in data.columns]

In [28]:
data.loc[data["label"] == "n", "label"] = 0
data.loc[data["label"] == "t", "label"] = 1
data["label"] = data["label"].astype(int)
data.head(3)

,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,label
0,8589.42,5468.24,4263.41,4064.94,1997.89,5282.33,2169.72,2773.42,7526.39,4607.68,...,67.56,259.91,138.90,88.23,39.67,67.83,75.68,83.52,28.70,1
1,9164.25,6719.53,4883.45,3718.16,2015.22,5569.91,3849.06,2793.39,7017.73,4802.25,...,92.24,96.28,150.59,82.24,85.03,152.20,186.57,44.47,16.77,0
2,3825.71,6970.36,5369.97,4705.65,1166.55,1572.17,1325.40,1472.26,3296.95,2786.58,...,82.72,31.10,193.92,76.97,224.62,31.23,42.66,16.09,15.16,1

In [29]:
train_data, test_data = train_test_split(data, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=data["label"])

In [30]:
train_data["subset"] = "train"
test_data["subset"] = "test"
data = pd.concat([train_data, test_data], axis=0).reset_index(drop=True)
data.columns = [col[0] if isinstance(col, tuple) else col for col in data.columns]
data["label"] = data["label"].astype(int)
data

,0,1,2,3,4,5,6,7,8,9,...,1992,1993,1994,1995,1996,1997,1998,1999,label,subset
0,7666.68,6409.74,6489.86,2451.12,4176.21,4654.64,2321.52,3520.32,4477.45,7184.07,...,601.85,117.00,62.32,167.31,13.27,52.09,47.72,30.42,1,train
1,6951.35,5565.78,4480.79,3667.65,4278.62,7568.93,6299.36,5174.09,4038.19,4831.83,...,624.73,155.82,173.11,297.49,228.81,140.87,66.44,73.62,1,train
2,4865.22,3237.78,2341.09,2372.68,3058.27,1347.13,1306.57,3507.05,3917.27,1528.61,...,88.16,15.69,52.94,26.89,34.63,33.04,36.90,64.52,0,train
3,14876.41,3201.90,2327.63,11248.68,5893.28,5319.86,9939.25,4058.64,14144.84,3282.62,...,554.19,65.20,277.21,442.79,377.84,335.16,116.66,58.66,1,train
4,8753.24,8978.13,7777.84,6202.50,4271.41,8248.88,5514.24,3681.19,7043.59,12307.91,...,558.85,257.39,204.83,702.13,75.26,192.89,95.84,117.20,1,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,4214.90,2213.36,1611.52,1764.23,4374.78,4520.79,3982.80,3466.29,2197.63,2560.50,...,431.87,20.47,31.60,88.52,19.13,28.82,20.33,94.55,1,test
58,5627.25,3619.53,2606.50,2544.45,5967.09,7736.47,4633.87,1356.45,2982.88,6400.23,...,190.26,68.48,52.22,12.06,9.19,18.02,8.45,37.82,0,test
59,9443.88,6671.78,6260.62,4905.71,3139.25,10926.22,7376.85,3245.25,6518.74,5336.10,...,522.58,330.31,293.45,149.93,240.61,247.30,197.22,95.60,1,test
60,6357.92,3736.85,2665.59,2493.88,1306.25,4092.72,3163.86,1077.62,3865.81,1923.37,...,162.02,114.83,98.47,111.51,82.04,146.48,72.51,14.29,1,test
61,3825.71,6970.36,5369.97,4705.65,1166.55,1572.17,1325.40,1472.26,3296.95,2786.58,...,31.10,193.92,76.97,224.62,31.23,42.66,16.09,15.16,1,test

In [31]:
data.drop(columns=["subset"]).dtypes.unique(), data["label"].value_counts(normalize=True), data["subset"].value_counts(normalize=True), data.groupby("subset")["label"].value_counts(normalize=True), data.isna().sum().sum()

(array([dtype('float64'), dtype('int64')], dtype=object),
 label
 1    0.645161
 0    0.354839
 Name: proportion, dtype: float64,
 subset
 train    0.693548
 test     0.306452
 Name: proportion, dtype: float64,
 subset  label
 test    1        0.631579
         0        0.368421
 train   1        0.651163
         0        0.348837
 Name: proportion, dtype: float64,
 np.int64(0))

In [32]:
data.to_parquet("../Benchmark/alon1999.parquet", index=False)

# DLBCL

Source: https://github.com/lsgo-metaheuristics/ACCFS/blob/main/dataset1/dlbcl.zip

In [5]:
data = pd.read_csv("../Datasets/dlbcl/dlbcl.csv", header=None)
data

,0,1,2,3,4,5,6,7,8,9,...,5460,5461,5462,5463,5464,5465,5466,5467,5468,5469
0,0.144361,0.180113,0.205273,0.645511,0.158865,0.220173,0.014810,0.050187,0.175623,0.808613,...,0.131643,0.363919,0.295554,0.068462,0.273121,0.137020,0.178820,0.553937,0.902423,1
1,0.457143,0.113693,0.297552,0.589472,0.053901,0.665130,0.118183,0.088879,0.519780,0.024620,...,0.254293,0.192846,0.191609,0.783389,0.294798,0.703769,0.537330,0.400216,0.897839,1
2,0.187970,0.070903,0.186441,0.653968,0.147518,0.734524,0.098907,0.184019,0.334553,0.650066,...,0.291087,0.384137,0.329994,0.555930,0.326590,0.295174,0.287804,0.599245,0.925344,1
3,0.000000,0.262825,0.246704,0.560307,0.042080,0.301671,0.707099,1.000000,0.469472,0.103051,...,0.176615,0.017107,0.039449,0.347175,0.101156,0.389398,0.253322,0.529666,0.859201,1
4,0.219549,0.150917,0.271186,0.606623,0.082033,0.322882,0.207276,0.345234,0.796936,0.144833,...,0.376124,0.211509,0.450219,0.137673,0.182081,0.061641,0.190209,0.471413,0.910282,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,0.302256,0.252309,0.195857,0.510512,0.268322,0.230663,0.009109,0.052150,0.141093,0.205782,...,0.167621,0.129082,0.157170,0.077067,0.686416,0.133145,0.140541,0.340885,0.727570,0
73,0.321805,0.275089,0.510358,0.331568,0.335461,0.358040,0.159732,0.095514,0.224331,0.359317,...,0.283729,0.762053,0.478397,0.064721,0.671965,0.241458,0.082964,0.820928,0.865750,0
74,0.356391,0.147482,0.148776,0.455738,0.269740,0.259481,0.618535,0.484579,1.000000,0.432255,...,0.165985,0.105754,0.316844,0.071081,0.498555,0.055477,0.150902,0.297735,0.755730,0
75,0.341353,0.218742,0.111111,0.301296,0.176596,0.125879,0.004995,0.045047,0.161674,0.490477,...,0.082584,0.312597,0.251096,0.041900,0.427746,0.042797,0.084862,0.441208,0.836935,0
76,0.258647,0.329775,0.308851,0.622985,0.066194,0.016023,0.035378,0.045794,0.114109,0.157745,...,0.270646,0.472784,0.458986,0.024317,0.500000,0.200951,0.102895,0.741640,0.899804,0

In [14]:
data.rename(columns={data.shape[1]-1: "label"}, inplace=True)

In [15]:
data

,0,1,2,3,4,5,6,7,8,9,...,5460,5461,5462,5463,5464,5465,5466,5467,5468,label
0,0.144361,0.180113,0.205273,0.645511,0.158865,0.220173,0.014810,0.050187,0.175623,0.808613,...,0.131643,0.363919,0.295554,0.068462,0.273121,0.137020,0.178820,0.553937,0.902423,1
1,0.457143,0.113693,0.297552,0.589472,0.053901,0.665130,0.118183,0.088879,0.519780,0.024620,...,0.254293,0.192846,0.191609,0.783389,0.294798,0.703769,0.537330,0.400216,0.897839,1
2,0.187970,0.070903,0.186441,0.653968,0.147518,0.734524,0.098907,0.184019,0.334553,0.650066,...,0.291087,0.384137,0.329994,0.555930,0.326590,0.295174,0.287804,0.599245,0.925344,1
3,0.000000,0.262825,0.246704,0.560307,0.042080,0.301671,0.707099,1.000000,0.469472,0.103051,...,0.176615,0.017107,0.039449,0.347175,0.101156,0.389398,0.253322,0.529666,0.859201,1
4,0.219549,0.150917,0.271186,0.606623,0.082033,0.322882,0.207276,0.345234,0.796936,0.144833,...,0.376124,0.211509,0.450219,0.137673,0.182081,0.061641,0.190209,0.471413,0.910282,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,0.302256,0.252309,0.195857,0.510512,0.268322,0.230663,0.009109,0.052150,0.141093,0.205782,...,0.167621,0.129082,0.157170,0.077067,0.686416,0.133145,0.140541,0.340885,0.727570,0
73,0.321805,0.275089,0.510358,0.331568,0.335461,0.358040,0.159732,0.095514,0.224331,0.359317,...,0.283729,0.762053,0.478397,0.064721,0.671965,0.241458,0.082964,0.820928,0.865750,0
74,0.356391,0.147482,0.148776,0.455738,0.269740,0.259481,0.618535,0.484579,1.000000,0.432255,...,0.165985,0.105754,0.316844,0.071081,0.498555,0.055477,0.150902,0.297735,0.755730,0
75,0.341353,0.218742,0.111111,0.301296,0.176596,0.125879,0.004995,0.045047,0.161674,0.490477,...,0.082584,0.312597,0.251096,0.041900,0.427746,0.042797,0.084862,0.441208,0.836935,0
76,0.258647,0.329775,0.308851,0.622985,0.066194,0.016023,0.035378,0.045794,0.114109,0.157745,...,0.270646,0.472784,0.458986,0.024317,0.500000,0.200951,0.102895,0.741640,0.899804,0

In [16]:
train_data, test_data = train_test_split(data, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=data["label"])
train_data["subset"] = "train"
test_data["subset"] = "test"
data = pd.concat([train_data, test_data], axis=0, ignore_index=True)
data

,0,1,2,3,4,5,6,7,8,9,...,5461,5462,5463,5464,5465,5466,5467,5468,label,subset
0,0.000000,0.262825,0.246704,0.560307,0.042080,0.301671,0.707099,1.000000,0.469472,0.103051,...,0.017107,0.039449,0.347175,0.101156,0.389398,0.253322,0.529666,0.859201,1,train
1,0.181955,0.091959,0.203390,0.225261,0.012293,0.110432,0.072285,0.092150,0.422136,0.005052,...,0.068429,0.076393,0.871306,0.210983,0.060937,0.325214,0.411543,0.793713,1,train
2,0.258647,0.329775,0.308851,0.622985,0.066194,0.016023,0.035378,0.045794,0.114109,0.157745,...,0.472784,0.458986,0.024317,0.500000,0.200951,0.102895,0.741640,0.899804,0,train
3,0.162406,0.076419,0.156309,0.597771,0.066194,0.567262,0.061530,0.110187,0.435856,0.066603,...,0.146190,0.192862,0.479985,0.150289,0.195139,0.407387,0.577131,0.928618,1,train
4,0.356391,0.206785,0.256121,0.643535,0.174941,0.208646,0.017807,0.053271,0.172422,0.451742,...,0.191291,0.212273,0.118593,0.261561,0.059704,0.111832,0.500000,0.916830,1,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,0.142857,0.223359,0.169492,0.437480,0.097163,0.053718,0.006229,0.047570,0.102218,0.467902,...,0.611198,0.449593,0.080060,0.488439,0.092990,0.075767,0.351672,0.713163,0,test
73,0.362406,0.190678,0.222222,0.654600,0.197872,0.219597,0.012459,0.053738,0.144066,0.739805,...,0.199067,0.258610,0.052376,0.355491,0.087179,0.159443,0.523193,0.893910,0,test
74,0.099248,0.209937,0.160075,0.626857,0.128842,0.114006,0.026622,0.094299,0.397210,0.654397,...,0.317263,0.081403,0.213618,0.197977,0.063579,0.110250,0.510787,0.895219,1,test
75,0.198496,0.227989,0.071563,0.574455,0.346809,0.500519,0.006641,0.052336,0.145895,0.786880,...,0.073095,0.097683,0.404040,0.511561,0.079253,0.217574,0.258900,0.722986,1,test
76,0.302256,0.252309,0.195857,0.510512,0.268322,0.230663,0.009109,0.052150,0.141093,0.205782,...,0.129082,0.157170,0.077067,0.686416,0.133145,0.140541,0.340885,0.727570,0,test

In [ ]:
data.drop(columns=["subset"]).dtypes.unique(), data["label"].value_counts(normalize=True), data["subset"].value_counts(normalize=True), data.groupby("subset")["label"].value_counts(normalize=True), data.isna().sum().sum()

(label
 1    0.753247
 0    0.246753
 Name: proportion, dtype: float64,
 subset
 train    0.688312
 test     0.311688
 Name: proportion, dtype: float64,
 subset  label
 test    1        0.750000
         0        0.250000
 train   1        0.754717
         0        0.245283
 Name: proportion, dtype: float64,
 np.int64(0))

In [18]:
data.to_parquet("../Benchmark/dlbcl.parquet", index=False)

# Prostate Tumor 1

Source: https://github.com/lsgo-metaheuristics/ACCFS/blob/main/dataset1/prostate_tumor_1.zip

In [19]:
data = pd.read_csv("../Datasets/prostate_tumor_1/prostate_tumor_1.csv", header=None)
data

,0,1,2,3,4,5,6,7,8,9,...,5957,5958,5959,5960,5961,5962,5963,5964,5965,5966
0,0.076910,0.162736,0.266541,0.000000,0.042489,0.348007,0.111080,0.129614,0.319706,0,...,0.0,0.0,0.085065,0.576969,0.000000,0.328565,0.148087,0.230652,0.727986,0
1,0.000000,0.000000,0.121278,0.000000,0.198944,0.000000,0.000000,0.112278,0.000000,0,...,0.0,0.0,0.000000,0.250648,0.000000,0.000000,0.000000,0.000000,0.528406,0
2,0.720341,0.735775,0.000000,0.493612,0.358241,0.862921,0.904333,0.416196,0.712657,0,...,0.0,0.0,0.376515,0.705750,0.127497,0.719158,0.000000,0.000000,0.000000,0
3,0.179269,0.331117,0.961226,0.051344,0.555485,0.777351,0.620422,0.281846,0.586693,0,...,0.0,0.0,0.138260,0.751632,0.315609,0.507582,0.403275,0.000000,0.000000,0
4,0.601733,0.408929,0.000000,0.098218,0.610837,0.784492,0.595295,0.594396,0.461710,0,...,0.0,0.0,0.304871,0.654998,0.222726,0.643911,0.511922,0.385382,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078481,0.000000,0,...,0.0,0.0,0.263745,0.409038,0.505863,0.000000,0.000000,0.000000,0.484142,1
98,0.000000,0.117090,0.187427,0.000000,0.000000,0.000000,0.121930,0.388611,0.000000,0,...,0.0,0.0,0.166610,0.316323,0.000000,0.000000,0.000000,0.000000,0.383317,1
99,0.000000,0.000000,0.121278,0.000000,0.000000,0.000000,0.000000,0.526089,0.000000,0,...,0.0,0.0,0.263745,0.326016,0.000000,0.000000,0.000000,0.000000,0.484142,1
100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.115807,0.000000,0,...,0.0,0.0,0.000000,0.262623,0.000000,0.000000,0.000000,0.000000,0.506717,1
101,0.000000,0.000000,0.187427,0.000000,0.000000,0.000000,0.000000,0.202250,0.000000,0,...,0.0,0.0,0.000000,0.238185,0.127497,0.000000,0.000000,0.000000,0.410298,1

In [20]:
data.rename(columns={data.shape[1]-1: "label"}, inplace=True)

In [21]:
train_data, test_data = train_test_split(data, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=data["label"])
train_data["subset"] = "train"
test_data["subset"] = "test"
data = pd.concat([train_data, test_data], axis=0, ignore_index=True)
data

,0,1,2,3,4,5,6,7,8,9,...,5958,5959,5960,5961,5962,5963,5964,5965,label,subset
0,0.000000,0.000000,0.084278,0.000000,0.176214,0.336011,0.000000,0.346791,0.000000,0,...,0.0,0.218041,0.370340,0.000000,0.000000,0.000000,0.206190,0.588795,0,train
1,0.000000,0.000000,0.121278,0.000000,0.000000,0.000000,0.000000,0.338394,0.000000,0,...,0.0,0.000000,0.197418,0.036115,0.000000,0.000000,0.000000,0.383317,1,train
2,0.422463,0.309343,0.000000,0.000000,0.469687,0.423999,0.461599,0.143605,0.392584,0,...,0.0,0.323986,0.564995,0.315609,0.371254,0.233538,0.000000,0.000000,1,train
3,0.439149,0.309343,0.000000,0.218427,0.695965,0.526909,0.525803,0.186539,0.332705,0,...,0.0,0.000000,0.620658,0.315609,0.445125,0.000000,0.260264,0.436024,1,train
4,0.000000,0.000000,0.342962,0.000000,0.000000,0.438922,0.000000,0.243054,0.042740,0,...,0.0,0.000000,0.496868,0.000000,0.073871,0.000000,0.276583,0.325051,1,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,0.000000,0.000000,0.155535,0.000000,0.000000,0.000000,0.000000,0.243561,0.000000,0,...,0.0,0.000000,0.094691,0.000000,0.000000,0.000000,0.000000,0.354951,0,test
98,0.368257,0.331117,0.629114,0.471621,0.458819,0.000000,0.000000,0.465853,0.000000,0,...,0.0,0.451433,0.753990,0.000000,0.507582,0.258695,0.000000,0.569389,0,test
99,0.283785,0.081368,0.000000,0.000000,0.595838,0.000000,0.344805,0.278614,0.287825,0,...,0.0,0.392631,0.617002,0.178095,0.431389,0.080243,0.550255,0.224226,1,test
100,0.000000,0.117090,0.715364,0.000000,0.447627,0.280248,0.273165,0.299230,0.181822,0,...,0.0,0.502864,0.651733,0.243213,0.402436,0.115471,0.260264,0.293442,1,test
101,0.000000,0.000000,0.459132,0.000000,0.000000,0.000000,0.121930,0.333187,0.081758,0,...,0.0,0.039164,0.462269,0.178095,0.038617,0.000000,0.000000,0.460606,1,test

In [ ]:
data.drop(columns=["subset"]).dtypes.unique(), data["label"].value_counts(normalize=True), data["subset"].value_counts(normalize=True), data.groupby("subset")["label"].value_counts(normalize=True), data.isna().sum().sum()

(label
 1    0.509804
 0    0.490196
 Name: proportion, dtype: float64,
 subset
 train    0.696078
 test     0.303922
 Name: proportion, dtype: float64,
 subset  label
 test    1        0.516129
         0        0.483871
 train   1        0.507042
         0        0.492958
 Name: proportion, dtype: float64,
 np.int64(0))

In [23]:
data.to_parquet("../Benchmark/prostate_tumor_1.parquet", index=False)

# GFE

Source: https://github.com/lsgo-metaheuristics/ACCFS/tree/main/dataset2

In [9]:
train_data = pd.read_csv("../Datasets/Grammatical Facial Expression/grammatical_facial_expression01_training.txt", sep="  ", engine="python", header=None)
train_data.rename(columns={train_data.columns[-1]: "label"}, inplace=True)
train_data["label"] = train_data["label"].astype(int)
train_data["subset"] = "train"
train_data

,0,1,2,3,4,5,6,7,8,9,...,293,294,295,296,297,298,299,300,label,subset
0,1.390386e+09,291.098,205.121,1204.0,288.391,203.375,1208.0,284.995,202.883,1212.0,...,189.438,1256.0,325.014,192.472,1265.0,327.901,195.855,1265.0,0,train
1,1.390386e+09,292.192,204.955,1200.0,289.389,202.732,1195.0,285.757,201.953,1208.0,...,190.017,1247.0,328.621,193.891,1256.0,331.393,198.008,1329.0,0,train
2,1.390386e+09,291.093,204.574,1212.0,288.374,202.749,1212.0,284.956,202.178,1221.0,...,190.290,1256.0,325.672,193.341,1265.0,328.554,196.748,1275.0,0,train
3,1.390386e+09,293.701,206.100,1204.0,290.965,204.149,1204.0,287.462,203.471,1204.0,...,192.104,1243.0,329.291,195.265,1256.0,332.165,198.772,0.0,0,train
4,1.390386e+09,294.731,208.576,1187.0,291.999,206.223,1183.0,288.358,205.315,1187.0,...,194.358,1234.0,331.914,197.913,1247.0,334.685,201.834,1252.0,1,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,1.390386e+09,294.214,214.504,1179.0,291.512,212.667,1179.0,287.906,212.050,1191.0,...,199.632,1221.0,328.732,201.113,1238.0,332.266,203.429,1247.0,1,train
739,1.390386e+09,292.511,204.077,1200.0,289.871,202.242,1200.0,286.493,201.633,1204.0,...,189.999,1243.0,326.286,192.793,1252.0,329.337,195.989,1256.0,0,train
740,1.390386e+09,293.318,208.051,1187.0,290.476,205.775,1187.0,286.766,205.025,1191.0,...,192.646,1238.0,330.255,196.175,0.0,333.160,200.155,0.0,0,train
741,1.390386e+09,291.062,206.339,1195.0,288.341,204.448,1200.0,284.870,203.837,1204.0,...,190.565,1243.0,325.997,193.397,1252.0,328.973,196.711,1252.0,0,train
742,1.390386e+09,296.728,208.919,1187.0,294.060,206.696,1183.0,290.508,205.862,1191.0,...,194.165,1234.0,333.219,197.524,1252.0,335.895,201.265,0.0,1,train

In [10]:
test_data = pd.read_csv("../Datasets/Grammatical Facial Expression/grammatical_facial_expression01_testing.txt", sep="  ", engine="python", header=None)
test_data.rename(columns={test_data.columns[-1]: "label"}, inplace=True)
test_data["label"] = test_data["label"].astype(int)
test_data["subset"] = "test"
test_data

,0,1,2,3,4,5,6,7,8,9,...,293,294,295,296,297,298,299,300,label,subset
0,1.390386e+09,295.012,210.126,1187.0,292.259,208.049,1183.0,288.707,207.325,1195.0,...,194.515,1229.0,330.841,197.620,1243.0,333.772,201.167,1252.0,1,test
1,1.390386e+09,291.366,204.306,1212.0,288.612,202.541,1216.0,285.167,202.021,1221.0,...,189.890,1261.0,325.896,193.130,1270.0,328.685,196.655,1280.0,0,test
2,1.390386e+09,291.942,203.606,1204.0,289.261,201.530,1204.0,285.796,200.776,1212.0,...,189.777,1247.0,327.102,193.097,1256.0,329.973,196.736,1256.0,0,test
3,1.390386e+09,292.529,204.184,1200.0,289.895,202.347,1204.0,286.531,201.730,1204.0,...,190.091,1243.0,326.280,192.813,1256.0,329.366,195.965,1256.0,0,test
4,1.390386e+09,293.865,204.021,1204.0,291.124,201.897,1204.0,287.591,201.135,1208.0,...,189.678,1252.0,330.273,193.571,1270.0,332.900,197.629,0.0,0,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,1.390386e+09,292.519,212.782,1179.0,289.771,210.597,1175.0,286.061,209.818,1183.0,...,198.040,1225.0,327.988,200.447,1238.0,331.393,203.536,0.0,1,test
315,1.390386e+09,293.842,207.500,1191.0,290.975,205.303,1191.0,287.294,204.582,1200.0,...,191.902,1234.0,330.744,195.370,1252.0,333.716,199.299,1309.0,0,test
316,1.390386e+09,293.912,206.063,1204.0,291.186,204.071,1204.0,287.687,203.365,1208.0,...,192.138,1247.0,329.621,195.406,1256.0,332.435,198.995,0.0,0,test
317,1.390386e+09,292.335,203.976,1208.0,289.586,202.054,1208.0,286.155,201.453,1212.0,...,188.698,1252.0,327.332,192.217,1265.0,330.096,196.022,1261.0,0,test
318,1.390386e+09,294.914,214.986,1175.0,292.198,212.658,1175.0,288.458,211.774,1187.0,...,201.267,1234.0,331.392,203.981,1247.0,334.533,207.300,0.0,1,test

In [11]:
data = pd.concat([train_data, test_data], axis=0, ignore_index=True)
data

,0,1,2,3,4,5,6,7,8,9,...,293,294,295,296,297,298,299,300,label,subset
0,1.390386e+09,291.098,205.121,1204.0,288.391,203.375,1208.0,284.995,202.883,1212.0,...,189.438,1256.0,325.014,192.472,1265.0,327.901,195.855,1265.0,0,train
1,1.390386e+09,292.192,204.955,1200.0,289.389,202.732,1195.0,285.757,201.953,1208.0,...,190.017,1247.0,328.621,193.891,1256.0,331.393,198.008,1329.0,0,train
2,1.390386e+09,291.093,204.574,1212.0,288.374,202.749,1212.0,284.956,202.178,1221.0,...,190.290,1256.0,325.672,193.341,1265.0,328.554,196.748,1275.0,0,train
3,1.390386e+09,293.701,206.100,1204.0,290.965,204.149,1204.0,287.462,203.471,1204.0,...,192.104,1243.0,329.291,195.265,1256.0,332.165,198.772,0.0,0,train
4,1.390386e+09,294.731,208.576,1187.0,291.999,206.223,1183.0,288.358,205.315,1187.0,...,194.358,1234.0,331.914,197.913,1247.0,334.685,201.834,1252.0,1,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,1.390386e+09,292.519,212.782,1179.0,289.771,210.597,1175.0,286.061,209.818,1183.0,...,198.040,1225.0,327.988,200.447,1238.0,331.393,203.536,0.0,1,test
1058,1.390386e+09,293.842,207.500,1191.0,290.975,205.303,1191.0,287.294,204.582,1200.0,...,191.902,1234.0,330.744,195.370,1252.0,333.716,199.299,1309.0,0,test
1059,1.390386e+09,293.912,206.063,1204.0,291.186,204.071,1204.0,287.687,203.365,1208.0,...,192.138,1247.0,329.621,195.406,1256.0,332.435,198.995,0.0,0,test
1060,1.390386e+09,292.335,203.976,1208.0,289.586,202.054,1208.0,286.155,201.453,1212.0,...,188.698,1252.0,327.332,192.217,1265.0,330.096,196.022,1261.0,0,test
1061,1.390386e+09,294.914,214.986,1175.0,292.198,212.658,1175.0,288.458,211.774,1187.0,...,201.267,1234.0,331.392,203.981,1247.0,334.533,207.300,0.0,1,test

In [12]:
data.drop(columns=["subset"]).dtypes.unique(), data["label"].value_counts(normalize=True), data["subset"].value_counts(normalize=True), data.groupby("subset")["label"].value_counts(normalize=True), data.isna().sum().sum()

(array([dtype('float64'), dtype('int64')], dtype=object),
 label
 0    0.610169
 1    0.389831
 Name: proportion, dtype: float64,
 subset
 train    0.699623
 test     0.300377
 Name: proportion, dtype: float64,
 subset  label
 test    0        0.586207
         1        0.413793
 train   0        0.620458
         1        0.379542
 Name: proportion, dtype: float64,
 np.int64(0))

In [13]:
data.to_parquet("../Benchmark/gfe.parquet", index=False)